<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="src/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>


<body>



<h1>Modèle de conditions générales du site BookYourBouquet.com</h1>

<p>Les présentes conditions de vente sont conclues d’une part par la société BookYourBouquet au capital social de 100000000€ dont le siège social est situé à Strasbourg, immatriculée au Registre du Commerce et des Sociétés de Strasbourg sous le numéro 123456789 ci-après dénommée "BookYourBouquet" et gérant le site BookYourBouquet.com et, d’autre part, par toute personne physique ou morale souhaitant procéder à un achat via le site internet BookYourBouquet.com dénommée ci-après " l’acheteur ".</p>
<h2>Article 1. Objet </h2>
<p>Les présentes conditions de vente visent à définir les relations contractuelles entre BookYourBouquet et l’acheteur et les conditions applicables à tout achat effectué par le biais du site internet BookYourBouquet.com. L’acquisition d’un produit à travers le présent site implique une acceptation sans réserve par l’acheteur des présentes conditions de vente dont l’acheteur reconnaît avoir pris connaissance préalablement à sa commande. Avant toute transaction, l’acheteur déclare d’une part que l’achat de produits sur le site BookYourBouquet.com est sans rapport direct avec son activité professionnelle et est limité à une utilisation strictement personnelle et d’autre part avoir la pleine capacité juridique, lui permettant de s’engager au titre des présentes conditions générales de ventes.
    La société BookYourBouquet conserve la possibilité de modifier à tout moment ces conditions de ventes, afin de respecter toute nouvelle réglementation ou dans le but d'améliorer l’utilisation de son site. De ce fait, les conditions applicables seront celles en vigueur à la date de la commande par l’acheteur.</p>
<h2>Article 2. Produits </h2>
<p>Les produits proposés sont ceux qui figurent sur le site BookYourBouquet.com de la société BookYourBouquet, dans la limite des stocks disponibles. La société BookYourBouquet se réserve le droit de modifier à tout moment l’assortiment de produits. Chaque produit est présenté sur le site internet sous forme d’un descriptif reprenant ses principales caractéristiques techniques (contenance, utilisation, composition…). Les photographies sont les plus fidèles possibles mais n’engagent en rien le Vendeur. La vente des produits présentés dans le site BookYourBouquet.com est destinée à tous les acheteurs résidants dans les pays qui autorisent pleinement l’entrée sur leur territoire de ces produits. (à modifier éventuellement)</p>
<h2>Article 3. Tarifs </h2>
<p>Les prix figurant sur les fiches produits du catalogue internet et sont des prix en Euros (€) toutes taxes comprises (TTC) tenant compte de la TVA applicable au jour de la commande. Tout changement du taux de la TVA pourra être répercuté sur le prix des produits. La société BookYourBouquet se réserve le droit de modifier ses prix à tout moment, étant toutefois entendu que le prix figurant au catalogue le jour de la commande sera le seul applicable à l’acheteur. </p>
<h2>Article 4. Commande et modalités de paiement </h2>
<p>La société BookYourBouquet propose à l’acheteur de commander et régler ses produits en plusieurs étapes, avec 2 options de paiement :</p>
<h2>- Paiement par virement bancaire :</h2> <p>l’acheteur sélectionne les produits qu’il souhaite commander dans le « panier », modifie si besoin (quantités, références…), vérifie l’adresse de livraison ou en renseigne une nouvelle. Puis, les frais de port sont calculés et soumis à l’acheteur, ainsi que le nom du transporteur. Ensuite, l’acheteur choisit le mode de paiement de son choix : « Paiement par virement ». Enfin, la dernière étape lui propose de vérifier l’ensemble des informations, prendre connaissance et accepter les présentes conditions générales de vente en cochant la case correspondante, puis l’invite à valider sa commande en cliquant sur le bouton « Confirmer ma commande ». Ce dernier clic forme la conclusion définitive du contrat. Dès validation, l’acheteur reçoit un bon de commande confirmant l’enregistrement de sa commande. Afin de finaliser son paiement et déclencher le traitement de sa commande, l’acheteur doit contacter sa banque afin d'effectuer le virement correspondant au montant de sa commande vers le compte bancaire de ......................... (NOM SOCIÉTÉ), dont les coordonnées sont communiquées à l'acheteur. Dès réception du virement, la commande sera traitée et l’acheteur en sera informé par e-mail. La société ......................... (NOM SOCIÉTÉ) expédiera les produits au plus tôt 2 jours ouvrés après réception du virement correspondant à la commande, sous réserve de provisions.</p>
<h2>- Paiement sécurisé par Paypal ou carte bancaire (via le système PAYPAL) :</h2> <p>l’acheteur sélectionne les produits qu’il souhaite commander dans le « panier », modifie si besoin (quantités, références…), vérifie l’adresse de livraison ou en renseigne une nouvelle. Puis, les frais de port sont calculés et soumis à l’acheteur, ainsi que le nom du transporteur. Ensuite, l’acheteur choisit le mode de paiement de son choix : « Paiement par Paypal ». L’étape suivante lui propose de vérifier l’ensemble des informations, prendre connaissance et accepter les présentes conditions générales de vente en cochant la case correspondante, puis l’invite à valider sa commande en cliquant sur le bouton « Confirmer ma commande ». Enfin, l’acheteur est redirigé sur l’interface sécurisée PAYPAL afin de renseigner en toute sécurité ses références de compte Paypal ou de carte bleue personnelle. Si le paiement est accepté, la commande est enregistrée et le contrat définitivement formé. Le paiement par compte Paypal ou par carte bancaire est irrévocable. En cas d’utilisation frauduleuse de celle-ci, l’acheteur pourra exiger l’annulation du paiement par carte, les sommes versées seront alors recréditées ou restituées. La responsabilité du titulaire d’une carte bancaire n’est pas engagée si le paiement contesté a été prouvé effectué frauduleusement, à distance, sans utilisation physique de sa carte. Pour obtenir le remboursement du débit frauduleux et des éventuels frais bancaires que l’opération a pu engendrer, le porteur de la carte doit contester, par écrit, le prélèvement auprès de sa banque, dans les 70 jours suivant l’opération, voire 120 jours si le contrat le liant à celle-ci le prévoit. Les montants prélevés sont remboursés par la banque dans un délai maximum d’un mois après réception de la contestation écrite formée par le porteur. Aucun frais de restitution des sommes ne pourra être mis à la charge du titulaire.
    La confirmation d’une commande entraîne acceptation des présentes conditions de vente, la reconnaissance d’en avoir parfaite connaissance et la renonciation à se prévaloir de ses propres conditions d’achat. L’ensemble des données fournies et la confirmation enregistrée vaudront preuve de la transaction. Si l’acheteur possède une adresse électronique et s’il l’a renseignée sur son bon de commande, la société BookYourBouquet lui communiquera par courrier électronique la confirmation de l’enregistrement de sa commande.
    Si l’acheteur souhaite contacter la société BookYourBouquet, il peut le faire soit par courrier à l’adresse suivante : BookYourBouquet, 1 rue des Fleurs, 67000 Strasbourg; soit par email à l’adresse suivante : BookYourBouquet@gmail.com, soit par téléphone au 01 02 03 04 05.</p>
<h2>Article 5. Réserve de propriété </h2>
<p>La société BookYourBouquet conserve la propriété pleine et entière des produits vendus jusqu'au parfait encaissement du prix, en principal, frais et taxes compris.</p>
<h2>Article 6. Rétractation </h2>
<p>En vertu de l’article L121-20 du Code de la consommation, l’acheteur dispose d'un délai de quatorze jours ouvrables à compter de la livraison de leur commande pour exercer son droit de rétractation et ainsi faire retour du produit au vendeur pour échange ou remboursement sans pénalité, à l’exception des frais de retour.</p>
<h2>Article 7. Garantie </h2>
<p>Tous les produits fournis par la société BookYourBouquet bénéficient de la garantie légale prévue par les articles 1641 et suivants du Code civil. En cas de non conformité d’un produit vendu, il pourra être retourné à la société BookYourBouquet qui le reprendra, l’échangera ou le remboursera. Toutes les réclamations, demandes d’échange ou de remboursement doivent s’effectuer par voie postale à l’adresse suivante : BookYourBouquet, 1 rue des Fleurs, 67000 Strasbourg, dans un délai de trente jours après livraison.</p>
<h2>Article 8. Responsabilité </h2>
<p>La société BookYourBouquet, dans le processus de vente à distance, n’est tenue que par une obligation de moyens. Sa responsabilité ne pourra être engagée pour un dommage résultant de l’utilisation du réseau Internet tel que perte de données, intrusion, virus, rupture du service, ou autres problèmes involontaires.</p>
<h2>Article 9. Propriété intellectuelle </h2>
<p>Tous les éléments du site BookYourBouquet.com sont et restent la propriété intellectuelle et exclusive de la société BookYourBouquet. Personne n’est autorisé à reproduire, exploiter, ou utiliser à quelque titre que ce soit, même partiellement, des éléments du site qu’ils soient sous forme de photo, logo, visuel ou texte.</p>
<h2>Article 10. Données à caractère personnel</h2>
<p>La société BookYourBouquet s'engage à préserver la confidentialité des informations fournies par l’acheteur, qu'il serait amené à transmettre pour l'utilisation de certains services. Toute information le concernant est soumise aux dispositions de la loi n° 78-17 du 6 janvier 1978. A ce titre, l'internaute dispose d'un droit d'accès, de modification et de suppression des informations le concernant. Il peut en faire la demande à tout moment par courrier à l’adresse suivante :  BookYourBouquet, 1 rue des Fleurs, 67000 Strasbourg.</p>
<h2>Article 11. Règlement des litiges </h2>
<p>Les présentes conditions de vente à distance sont soumises à la loi française. Pour tous litiges ou contentieux, le Tribunal compétent sera celui de Strasbourg</p>

</body>
</html>
